// src/app/about/page.tsx
export default function About() {
	return (
		<div className="p-8 md:p-12 max-w-4xl">
			<div className="space-y-8">
				<div>
					<h1 className="page-header">
						About
					</h1>
					<div className="text-lg text-gray-400 leading-relaxed">
						<p className="mb-3">
							This site contains all the projects I am working on.
						</p>
						<div>
							<div className="flex gap-1">
								<p className="font-bold">repo:</p>
								<a
									className="underline line-clamp-1"
									target="_blank"
									href="https://github.com/edwardtanguay/edwards-projects"
								>
									https://github.com/edwardtanguay/edwards-projects
								</a>
							</div>
							<div className="flex gap-1">
								<p className="font-bold">live:</p>
								<a
									className="underline line-clamp-1"
									target="_blank"
									href="https://edwards-projects.vercel.app"
								>
									https://edwards-projects.vercel.app
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}

// app/pages/about/index.vue
<template>
  <p>This site contains all the projects I am working on.</p>
  <ul class="list-disc ml-6">
    <li>
      repo:
      <a
        class="underline"
        target="_blank"
        href="https://github.com/edwardtanguay/edwards-projects"
        >https://github.com/edwardtanguay/edwards-projects</a
      >
      <ul class="list-disc ml-6">
        <li>
          based on:
          <a
            class="underline"
            target="_blank"
            href="https://github.com/edwardtanguay/datapod-python-nuxt"
            >https://github.com/edwardtanguay/datapod-python-nuxt</a
          >
        </li>
      </ul>
    </li>
    <li>
      live:
      <a class="underline" target="_blank" href="https://edwards-projects.vercel.app"
        >https://edwards-projects.vercel.app</a
      >
    </li>
  </ul>
</template>
